### ISSUE TITLE
[Bug] Batch-Inference Template - Model name in Pipeline Not being passed

### ISSUE THREAD

**Issue by georschi** [aws-samples/sagemaker-custom-project-templates#8]
When deploying this template, using a model registry with an approved model, the deployed SageMaker Pipeline does not contain the name of the SageMaker Model to use for the Batch inference. 

The problem can be pinpointed in the cloudformation template in this line: 
https://github.com/aws-samples/sagemaker-custom-project-templates/blob/main/batch-inference/seedcode/endpoint-config-template.yml#L70

```yml
      PipelineDefinition: 
        PipelineDefinitionBody: !Sub
          - ${PipelineDefinitionBody}
          - { ModelName: !GetAtt ModelToDeploy.ModelName }
```
Which doesn't work as expected since cloudformation cannot essentially perform an nested substitution. 
Here the expectation is that the ${PipelineDefinitionBody} is substituted with the json value of the variable and then ModelName is replaces in that json. However, this "double" substitution is not possible with cloudFormation.
